config/routes.rb
Checkpup::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 

  resources :dogs

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Dog, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :destroy, Dog
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_many :owners, dependent: :destroy
  attr_accessible :age, :breed, :name, :needs, :weight, :dogimage 
  belongs_to :user
  mount_uploader :dogimage, ImageUploader 

  validates :name, length: { minimum: 5 }, presence: true
  validates :needs, length: { minimum: 20 }, presence: true
  validates :breed, length: { minimum: 5 }, presence: true
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :dog
  attr_accessible :email, :name, :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, :omniauthable
         #:validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  has_many :dogs

  before_create :set_member
  # attr_accessible :title, :body
  mount_uploader :avatar, AvatarUploader

  def self.find_for_instagram_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      #user.email = auth.info.email
      #user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      user.save!
    end
  end


  ROLES = %w[member moderator admin]
  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end  

  private

  def set_member
    self.role = 'member'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end 
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new 
    authorize! :create, Dog, message: "You need to be a member to create a new dog."
  end

 def create
    @dog = Dog.new(params[:dog])
    authorize! :create, @dog, message: "You need to be an admin to do that."
    if @dog.save
      flash[:notice] = "Dog was saved successfully."
      redirect_to @dog
    else
      flash[:error] = "Error creating dog. Please try again."
      render :new
    end
 end

  def edit
    @dog = Dog.find(params[:id])
    authorize! :edit, @dog, message: "You need to own the dog to edit it."
  end

  def update
    @dog = Dog.find(params[:id])
    authorize! :update, @dog, message: "You need to own the dog to edit it."
    if @dog.update_attributes(params[:dog])
      flash[:notice] = "Dog was updated."
      redirect_to @dog
    else
      flash[:error] = "There was an error saving the dog. Please try again."
      render :edit
    end
  end

  def destroy
    @dog= Dog.find(params[:id])
    name = @dog.name
    authorize! :destroy, @dog, message: "You need to own the dog to delete it."
    if @dog.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to dogs_path
    else
      flash[:error] = "There was an error deleting the dog."
      render :show
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def instagram
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_instagram_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Instagram") if is_navigational_format?
    else
      session["devise.instagram_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_form.html.erb
<%= form_for [dog], html: { class: 'form-horizontal' } do |f| %>
  <% if dog.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(dog.errors.count, "error") %>.</h4>
      <ul>
        <% dog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= control_group_tag(dog.errors[:title]) do %>
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  <% end %>
  <%= control_group_tag(dog.errors[:breed]) do %>
    <%= f.label :breed, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :breed %>
    </div>
  <% end %>
  <%= control_group_tag(dog.errors[:weight]) do %>
    <%= f.label :weight, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight %>
    </div>
  <% end %>
  <%= control_group_tag(dog.errors[:age]) do %>
    <%= f.label :age, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :age %>
    </div>
  <% end %>
  <%= control_group_tag(dog.errors[:body]) do %>
    <%= f.label :needs, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :needs, rows: 8 %>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :image, class: 'control-label' %>
    <div class="controls"> 
      <%= f.file_field :dogimage%>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Edit Dog</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new dogs:</p>
    <ul>
      <li>Make sure to fill out all of the fields completely</li>
      <li>Weigh each dog twice</li>
      <li>Check vet papers to compare the data</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { dog: @dog } %>
  </div>
</div>

app/views/dogs/index.html.erb
<h1>All of My Dogs</h1>

<% if can? :create, Dog %>
<%= link_to "New Dog", new_dog_path, class: 'btn btn-primary btn-mini' %>
<% end %>

<% @dogs.each do |dog| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to dog.name, dog %>
      </h4>
    </div>
  </div>
<% end %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new dogs:</p>
    <ul>
      <li>Make sure to fill out all of the fields completely</li>
      <li>Weigh each dog twice</li>
      <li>Check vet papers to compare the data</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { dog: @dog } %>
  </div>
</div>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

<% if can? :edit, @dog %>
  <%= link_to "Edit", edit_dog_path(@dog), class: 'btn btn-mini' %>
<% end %>

<p>Dog's needs: <%= @dog.needs %></p>
<p>Dog's weight: <%= @dog.weight %></p>
<p>Dog's breed: <%= @dog.breed %></p>
<p>Dog's age: <%= @dog.age %></p>
<p><%= image_tag(@dog.dogimage_url) if @dog.dogimage? %></p>

 <div class="span4">
<% if can? :destroy, @dog %>
  <%= link_to "Delete Dog", @dog, method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this dog?' %> 
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checkpup</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
      <li><%= link_to "Checkpup", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      </ul>

      <div class="pull-right user-info">
        <% if current_user %>
          <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
          Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Checkpup</h1>
<p>Created by: Brittany Martin</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title>Checkpup</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/stylesheets/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/stylesheets/main.css" rel="stylesheet">
    
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
    
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/smoothscroll.js"></script>
    

  </head>

  <body data-spy="scroll" data-offset="0" data-target="#navigation">

    <!-- Fixed navbar -->
      <div id="navigation" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><b>Checkpup</b></a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "About", about_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


  <section id="home" name="home"></section>
  <div id="headerwrap">
      <div class="container">
        <div class="row centered">
          <div class="col-lg-12">
          <h1><b>Checkpup</b></h1>
          <h3>Find the best boarding facility for your furry friend.</h3>
          <br>
          </div>
          
          <div class="col-lg-2">
            <h5>Who is it for?</h5>
            <p>CheckPup software is an easy-to-use tool tailored specifically for owners to find a boarding, grooming and/or dog daycare facility.</p>
            <%= image_tag("arrow1.png", class: "hidden-xs hidden-sm hidden-md") %>
          </div>
           <div class="col-lg-8">
            <%= image_tag("George1.png", class: "img-responsive") %>
           </div> 
          <div class="col-lg-2">
            <br>
            <%= image_tag("arrow2.png", class: "hidden-xs hidden-sm hidden-md") %>
            <h5>Images via Instagram</h5>
            <p>Facilities can see your pet before they arrive and see what they do for fun!</p>
          </div>
        </div>
      </div> <!--/ .container -->
  </div><!--/ #headerwrap -->

  <section id="desc" name="desc"></section>
  <!-- INTRO WRAP -->
  <div id="intro">
    <div class="container">
      <div class="row centered">
        <h1>Designed with Owners in Mind </h1>
        <br>
        <br>
        <div class="col-lg-4">
          <!--<img src="assets/img/intro01.png" alt=""> -->
          <%= image_tag("intro02.png") %>
          <h3>Visual Booking Calendar</h3>
          <p>View the itinery of your pet's stay</p>
        </div>
        <div class="col-lg-4">
          <!-- <img src="assets/img/intro02.png" alt=""> -->
          <%= image_tag("intro01.png") %>
          <h3>Fast</h3>
          <p>It's easy to locate partner facilities to find a special place for your loved one.</p>
        </div>
        <div class="col-lg-4">
          <!-- <img src="assets/img/intro03.png" alt=""> -->
          <%= image_tag("intro03.png") %>
          <h3>Security</h3>
          <p>Keep your pet's information at your fingertips with safe storage of your records.</p>
        </div>
      </div>
      <br>
      <hr>
      </div> <!--/ .container -->
  </div><!--/ #introwrap -->

  <div id="c">
    <div class="container">
      <br>
      <p>Design theme by <a href="http://www.blacktie.co">BLACKTIE.CO</a></p>
    </div>
  </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/js/bootstrap.js"></script>
  <script>
  $('.carousel').carousel({
    interval: 3500
  })
  </script>
  </body>
</html>